
# datasource??
#spring.datasource.url: jdbc:mysql:///(??????????????mysql)gaoxu???????
spring:
  datasource:
    url: jdbc:mysql:///gaoxu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 13948321033.GX
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

server:
  port: 8081

mybatis:
  type-aliases-package: com.gaoxu.springboot.pojo
  mapper-locations: classpath:mapper/*.xml

